name: CD

on:
  push:
    branches: [main]

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build ./backend -t vehicle-tracker-backend:${{ github.sha }}

      - name: Build frontend image
        run: docker build ./frontend -t vehicle-tracker-backend:${{ github.sha }}

